name: pda
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pyspark=3.5.0
  - pandas=2.0.3
  - numpy=1.24.3
  - matplotlib=3.7
  - seaborn=0.12
  - plotly=5.15
  - pyarrow=12.0.1
  - fastparquet=2023.7.0
  - openpyxl
  - pyyaml
  - psutil
  - pip
  - pip:
    - prometheus-client
    - pytest==7.4.0
    - pytest-cov==4.1.0
